---
version: '2'

services:
  proxy:
    image: proxy
    container_name: proxy
    hostname: "proxy"
    build: "proxy/"
    networks:
      - link
    ports:
      - "8080:80"

  web:
    image: nginx:1.13.1-alpine
    container_name: web
    hostname: "web"
    networks:
      - link

networks:
  link:
    driver: bridge
